### ISSUE TITLE
getUser() 비교가 안 되던 문제

### ISSUE THREAD

**Issue by uiseongsang** [itsinseo/LogTown#13]
# 문제
https://github.com/itsinseo/LogTown/blob/59a118fc2fd3c853f2e41237f1aa6d969352f873/src/main/java/com/sarida/logtown/service/PostServiceImpl.java#L49-L54
두개의 User가 동일 하지가 않아 예외처리로 빠져 나감

# 해결
https://github.com/itsinseo/LogTown/blob/59a118fc2fd3c853f2e41237f1aa6d969352f873/src/main/java/com/sarida/logtown/entity/User.java#L70-L78
equals Override

-> 본 해결이 옳은 방법이 아니므로
![image](https://github.com/itsinseo/LogTown/assets/40707686/1cfb4b67-80ef-4da6-a146-4bc019c35ebc)
두개의 유저는 동일하지만 passwordList의 문제로 유저1.equlas(유저2)가 동일 하지 않다고 나옴

# 다른 해결 방법
equals Override를 지우고 해당 객체의 PK에 해당하는 값을 비교
https://github.com/itsinseo/LogTown/blob/0fff10a3beefce9020b01c7dee2fbe295c3ddf11/src/main/java/com/sarida/logtown/service/PostServiceImpl.java#L49-L54

**Comment by Minji-Sohn2** [comment]
이슈 해결을 멋지게 해내셨네요!
